# Local configuration for open-webui
# You can overwrite all configutation parameters in this file
# Add environment variables here

#~ app_RAG_EMBEDDING_ENGINE=nomic-embed-text

#~ app_DEFAULT_LOCALE=fr

#~ OLLAMA_MODELS=llama3.2

#~ DOCLING_IMAGE_SRC=ghcr.io/docling-project/docling-serve-cu128:latest
#~ DOCLING_IMAGE_LANGS="eng,fra,deu"
#~ DOCLING_IMAGE=open-webui-docling-local
