# Local configuration for open-webui
# You can overwrite all configutation parameters in this file
# Add environment variables here

TESSERACT_LANG=fra

RAG_EMBEDDING_ENGINE=nomic-embed-text

DEFAULT_LOCALE=fr

OLLAMA_MODELS=llama3.2
