# Local configuration for open-webui
# You can overwrite all configutation parameters in this file
# Add environment variables here

app_TESSERACT_LANG=fra

#~ app_RAG_EMBEDDING_ENGINE=nomic-embed-text

app_DEFAULT_LOCALE=fr

OLLAMA_MODELS=llama3.2

OWEBUI_IMAGE_SRC=ghcr.io/open-webui/open-webui:cuda

OWEBUI_IMAGE_PKGS="tesseract-ocr tesseract-ocr-fra"

OWEBUI_IMAGE=open-webui-app-local
