# Conf for open-webui-postgrsql

# Image
SAMBA_IMAGE=dperson/samba

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ SAMBA_IMAGE_LARGE=--large

SAMBA_HOST=127.0.0.1

SAMBA_PORT_DS=445

SAMBA_PORT_SSN=139
