# Conf for open-webui-postgresql

# Image
POSTGRES_IMAGE=pgvector/pgvector:pg18-trixie

POSTGRES_PASSWORD=badpasswd

POSTGRES_USER=owebui

POSTGRES_DB=owebui_db

POSTGRES_HOST=127.0.0.1

POSTGRES_PORT=15432

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ POSTGRES_IMAGE_LARGE=--large
