# Conf for open-webui-ollama
# Look at full documentation https://docs.ollama.com/docker

OLLAMA_HOST=127.0.0.1

OLLAMA_PORT=11434

# For NVIDIA and Vulkan
OLLAMA_IMAGE=ollama/ollama

# AMD GPU
# OLLAMA_IMAGE=ollama/ollama:rocm

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ OLLAMA_IMAGE_LARGE=--large

# For NVIDIA
# If you’re running on an NVIDIA JetPack system, Ollama can’t automatically
# discover the correct JetPack version. Pass the environment variable
# JETSON_JETPACK=5 or JETSON_JETPACK=6 to the container to select version 5 or 6.
OLLAMA_DEVICE="--gpus all"

# AMD GPU
# DEVICE="--device /dev/kfd --device /dev/dri"

# Vulkan Support
# DEVICE="--device /dev/kfd --device /dev/dri -e OLLAMA_VULKAN=1"

OLLAMA_MODELS=llama3.2

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ OLLAMA_IMAGE_LARGE=--large
