# Conf for open-webui-glances
# Look at full documentation https://glances.readthedocs.io/en/latest/docker.html

GLANCES_HOST=127.0.0.1

GLANCES_PORT=61208

GLANCES_PORT_TCP=61209

# For monitoring gpus
GLANCES_IMAGE=nicolargo/glances:ubuntu-latest-full

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ GLANCES_IMAGE_LARGE=--large

# For monitoring gpus
GLANCES_DEVICE="--gpus all"

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ GLANCES_IMAGE_LARGE=--large
