# Conf for open-webui-app
OWEBUI_IMAGE=ghcr.io/open-webui/open-webui:main

# For nvidia
# OWEBUI_IMAGE=ghcr.io/open-webui/open-webui:cuda
# OWEBUI_DEVICE="--gpus all"
#~ OWEBUI_DEVICE=

OWEBUI_HOST=127.0.0.1

OWEBUI_PORT=8001

VECTOR_DB=pgvector

GLOBAL_LOG_LEVEL=WARNING
