# Conf for open-webui-goaccess

GOACCESS_IMAGE=allinurl/goaccess:latest

#~ GOACCESS_HOST=127.0.0.1

GOACCESS_PORT=7890

#GOACCESS_URL=webstats.example.com

goaccess_TZ=PST8PDT
goaccess_LANG=uk

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ GOACCESS_IMAGE_LARGE=--large
