# Conf for open-webui-app
#OWEBUI_IMAGE=ghcr.io/open-webui/open-webui:main
#~ OWEBUI_DEVICE=

# For nvidia
OWEBUI_IMAGE=ghcr.io/open-webui/open-webui:cuda
OWEBUI_DEVICE="--gpus all"

OWEBUI_HOST=127.0.0.1

OWEBUI_PORT=8080

app_VECTOR_DB=pgvector

app_GLOBAL_LOG_LEVEL=WARNING
