# Conf for open-webui-maxmind

MAXMIND_IMAGE=ghcr.io/maxmind/geoipupdate:latest

# Look at https://support.maxmind.com/knowledge-base/articles/create-a-maxmind-account#sign-up-for-geolite
# maxmind_GEOIPUPDATE_ACCOUNT_ID=REDACTED
# maxmind_GEOIPUPDATE_LICENSE_KEY=REDACTED

maxmind_GEOIPUPDATE_EDITION_IDS="GeoLite2-ASN GeoLite2-City GeoLite2-Country"

maxmind_GEOIPUPDATE_FREQUENCY=72

# For large image need to reduce dockerd max-concurrent-downloads to 1
#~ MAXMIND_IMAGE_LARGE=--large
