# Conf for open-webui-postgrsql

# Image
POSTGRES_IMAGE=pgvector/pgvector:pg18-trixie

# Image
POSTGRES_PASSWORD=badpasswd

POSTGRES_USER=owebui

POSTGRES_DB=owebui_db

POSTGRES_HOST=127.0.0.1

POSTGRES_PORT=15432
